version: '3'
services:
  db:
    build: ./db/
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data:Z
    env_file:
      - .env.development
    ports: 
      - "5433:5432"
    container_name: db
    networks:
      - db-network
  
  api:
    build: 
      context: .
      dockerfile: Dockerfile.deploy
    command: ash -c "bundle exec rails server -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/now-u-api
      - ../api-local/bundle/:/usr/local/bundle/
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env.development
    networks:
      - db-network
    # command: start.sh

  adminer:
    image: adminer
    networks:
      - db-network
    ports:
      - "3002:8080"
    depends_on:
      - db

volumes: 
  postgres:

networks:
  db-network:
    external: false
