version: '3'
services:
  db:
    build: ./db/
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data:Z
    env_file:
      - .env.development
      - .env.development.local
    ports: 
      - "5433:5432"
    container_name: db
    networks:
      - db-network
  
  api:
    build: 
      context: .
      dockerfile: docker/Dockerfile
      target: dev 
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
    env_file:
      - .env.development
    networks:
      - db-network
    command: /start

  meilisearch:
    image: getmeili/meilisearch
    networks:
      - db-network
    env_file:
      - .env.development
    ports:
      - 7700:7700
    volumes:
      - meilisearch:/data.ms

  adminer:
    image: adminer
    networks:
      - db-network
    ports:
      - "3002:8080"
    depends_on:
      - db

volumes: 
  postgres:
  meilisearch:

networks:
  db-network:
    external: false
