---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/campaigns/{id}":
    get:
      summary: Retrieves a campaign
      tags:
      - campaigns
      - Another Tag
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: campaign found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
                required:
                - id
                - title
                - content
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
                required:
                - id
                - title
                - content
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
