default: &default
  adapter: postgresql
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: now_u_test

production:
  <<: *default
