default: &default
  adapter: postgresql
  host: db
  username: test
  password: test
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: now_u_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: now_u_test

production:
  <<: *default
  database: <%= ENV['NOW_U_DATABASE_DATABASE'] %>
  username: <%= ENV['NOW_U_DATABASE_USERNAME'] %>
  password: <%= ENV['NOW_U_DATABASE_PASSWORD'] %>
  host: <%= ENV['NOW_U_DATABASE_HOST'] %>
  adapter: postgresql
  encoding: unicode
  pool: 5
