name: Build and push

inputs:
  services:  # id of input
    description: 'Space separated string of services to pull'
    required: true
  host:
    description: 'ssh host'
    required: true
  username:
    description: 'ssh username'
    required: true
  key:
    description: 'ssh key'
    required: true
  port:
    description: 'ssh port'
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy latest images
      uses: appleboy/ssh-action@master
      env:
        SERVICE_NAMES: ${{ inputs.services }}
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        port: ${{ inputs.port }}
        envs: SERVICE_NAMES
        script: |
          cd /var/sta
          docker-compose pull $SERVICE_NAMES
          docker-compose up -d $SERVICE_NAMES
          # TODO migrations
