name: Build and push

inputs:
  services:  # id of input
    description: 'Space separated string of services to pull'
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy latest images
      uses: appleboy/ssh-action@master
      env:
        SERVICE_NAMES: ${{ inputs.services }}
      with:
        host: ${{ secrets.SERVER_SSH_HOST }}
        username: ${{ secrets.SERVER_SSH_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        envs: SERVICE_NAMES
        script: |
          cd /var/sta
          docker-compose pull $SERVICE_NAMES
          docker-compose up -d $SERVICE_NAMES
          # TODO migrations
