name: Production Deployment 

on:
  push:
    branches:
      - main

jobs:
  pr-test:
    name: Run tests on pr 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repo 
        uses: actions/checkout@v2

      - name: Run the tests 
        uses: ./.github/workflows/test
      
      - name: Build image
        uses: ./.github/workflows/build
        with:
          image-name: 'api'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Deploy
        uses: ./.github/workflows/deploy
        with:
          services: 'api db'
