name: Test

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
    - name: Build docker images
      run: make build
      shell: bash

    - name: Run tests
      run: make test
      shell: bash
